version: '3.9'
services:
  api:
    image: node:alpine
    container_name: api
    working_dir: /app
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
